project: vault-wrapper
version: 0.3.4
author: Joel Lefkowitz
verbose_name: Vault wrapper
html_title: Vault wrapper 
github_url: https://github.com/JoelLefkowitz/vault-wrapper
apidoc_module_dir: vault-wrapper
